apiVersion: v1
kind: Secret
metadata:
  name: platform-credentials
  namespace: tasks-platform
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: distributed_platform
  DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/distributed_platform
  RABBITMQ_USER: platform
  RABBITMQ_PASS: platform
  RABBITMQ_URL: amqp://platform:platform@rabbitmq:5672/
  KEDA_RABBITMQ_URL: amqp://platform:platform@rabbitmq:5672/
  REDIS_URL: redis://redis:6379/0
  JWT_SECRET: change-me-in-prod
  ADMIN_PASSWORD: admin