apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tasks-platform
resources:
  - 00-namespace.yaml
  - 01-secrets.yaml
  - 02-configmap.yaml
  - 03-postgres.yaml
  - 04-rabbitmq.yaml
  - 05-redis.yaml
  - 06-backend.yaml
  - 07-worker.yaml
  - 08-hpa.yaml
  - 09-keda-rabbitmq.yaml